title : Atlanta Lindy Exchange
tagline: An exquisite lindy hop exchange in Atlanta
author :
  name : Jan Zheng
  email : contact@janzheng.com
  github : janzheng
  twitter : janistanian
  linkedin : www.linkedin.com/in/janzh # this probably needs to be configured somewhere


markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "notes.txt"]

kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: _sass
  style: :expanded
  # nested
  # expanded
  # compact
  # compressed
